# Spring properties
spring:
  application:
    name: notification-service
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
  data:
    mongodb:
      host: 192.168.0.101
      port: 27017
      database: notificationDB

# HTTP Server
server:
  port: 6060
#  servlet:
#    context-path: /user-service


#  eureka.instance.prefer-ip-address=true
#  eureka.instance.ip-address=
# Discovery Server Access
eureka:
  instance:
    preferIpAddress: true
    ip-address: 192.168.0.101
  client:
    serviceUrl:
      defaultZone: http://192.168.0.101:8080/discovery-server/eureka/
    instance:
      leaseRenewalIntervalInSeconds: false   # DO NOT DO THIS IN PRODUCTION
    registerWithEureka: true
    fetchRegistry: true

management:
  security:
    enabled: false



#http://localhost:9090/swagger-ui.html#/
#  http://localhost:6060/user/fetchAllCustomer


